<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>$schema</key>
    <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
    <key>name</key>
    <string>ADVPL</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#test</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#annotation-def</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#type-string</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>type-string</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>string.quoted.double.advpl</string>
            <key>match</key>
            <string>("[^"]*"?)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>string.quoted.double.advpl</string>
            <key>match</key>
            <string>('[^']*'?)</string>
          </dict>
        </array>
      </dict>
      <key>annotation-def</key>
      <dict>
        <key>begin</key>
        <string>(?i)^\s*(@annotation)\s+(\w+)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.class.advpl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.class.advpl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?i)(@end)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.class.advpl</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comentario</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#declaracao-metodo</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#annotation-property-def</string>
          </dict>
        </array>
      </dict>
      <key>annotation-property-def</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?i)(\w+)(?:\s+(as)\s+(?:(numeric|char|logical)))?\s+(?:(default))?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.object.property.advpl</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.control.as.advpl</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>storage.type.advpl</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>keyword.control.optional.advpl</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>test</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.directives.advpl-tlpp-header</string>
            <key>match</key>
            <string>(?i)#\b(define|endif|ifn?def|include|x?command|x?translate)\b</string>
          </dict>
        </array>
      </dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.block.advpl-tlpp-header</string>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.advpl-tlpp-header</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(^[ \t]+)?(?=//)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.whitespace.comment.leading.advpl-tlpp-header</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>comment.line.double-slash.advpl-tlpp-header</string>
                <key>begin</key>
                <string>//</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.advpl-tlpp-header</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(?=$)</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.advpl-tlpp-header</string>
  </dict>
</plist>