<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
        <string>prx</string>
		<string>prw</string>
		<string>prg</string>
		<string>ch</string>
	</array>
	<key>name</key>
	<string>advpl</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(?ix)
  \s*(function|procedure|method)
  \s*([_$a-zA-Z][$\w]*)?\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.harbour</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.harbour</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>e.g. function play(arg1, arg2) {  }</string>
			<key>end</key>
			<string>(?&lt;=\)|\n)</string>
			<key>name</key>
			<string>meta.function.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>numbers</string>
			<key>match</key>
			<string>\b(((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?))</string>
			<key>name</key>
			<string>constant.numeric.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>cadenas comillas simples</string>
			<key>match</key>
			<string>'[^']*'</string>
			<key>name</key>
			<string>string.quoted.single.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>cadenas comillas dobles</string>
			<key>match</key>
			<string>("[^"]*")</string>
			<key>name</key>
			<string>string.quoted.double.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>palavra chave</string>
			<key>match</key>
			<string>(?i)\b(?:do|case|endcase|otherwise|switch|if|else|elseif|endif|while|end|enddo|exit|static|function|return|for|next|include|ifdef|user|main|project|ifndef|class|endclass|new|method|data|from|local|static|public|user|public|main)\b</string>
			<key>name</key>
			<string>keyword.control.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>funcoes</string>
			<key>match</key>
			<string>(?i)\b(?:dbskip|dbseek|alias|dbusearea|dbcommit|dbselectarea|eof|bof|space|len)\b</string>
			<key>name</key>
			<string>keyword.control.harbour</string>
		</dict>
        <dict>
			<key>comment</key>
			<string>logical</string>
			<key>match</key>
			<string>(?i)\b(nil)</string>
			<key>name</key>
			<string>constant.numeric.advpl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.harbour</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>in-line comment with /* */</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.harbour</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.harbour</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>in-line comment with //</string>
			<key>match</key>
			<string>(//).*?($\n?|(?=\?&gt;))</string>
			<key>name</key>
			<string>comment.line.double-slash.harbour</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.advpl</string>
	<key>uuid</key>
	<string>56571807-d94d-4805-bbfc-87d347d189e4</string>
</dict>
</plist>